! Put your rules here in the format:
! old_biome > new_biome
! 
! Examples (remove ! in front of one to activate it):
! minecraft:dark_forest > minecraft:cherry_grove
! #minecraft:is_forest > minecraft:desert
! #terralith:skylands > null

minecraft:ocean > minecraft:desert
minecraft:cold_ocean > minecraft:desert
minecraft:deep_cold_ocean > minecraft:desert
minecraft:deep_frozen_ocean > minecraft:desert
minecraft:deep_lukewarm_ocean > minecraft:desert
minecraft:deep_ocean > minecraft:desert
minecraft:frozen_ocean > minecraft:desert
minecraft:lukewarm_ocean > minecraft:desert
minecraft:warm_ocean > minecraft:desert
terralith:deep_warm_ocean > minecraft:desert
terralith:warm_river > minecraft:desert
minecraft:river > minecraft:desert
minecraft:frozen_river > minecraft:desert
minecraft:snowy_plains > minecraft:plains
minecraft:ice_spikes > minecraft:plains
minecraft:snowy_taiga > minecraft:wooded_badlands
minecraft:grove > minecraft:wooded_badlands
minecraft:snowy_slopes > terralith:savanna_badlands
minecraft:frozen_peaks > terralith:bryce_canyon
minecraft:jagged_peaks > terralith:bryce_canyon
minecraft:snowy_beach > terralith:gravel_beach
minecraft:windswept_savanna > terralith:savanna_badlands
minecraft:windswept_forest > terralith:arid_highlands

terralith:alpha_islands_winter > minecraft:desert
terralith:alpine_grove > minecraft:wooded_badlands
terralith:terralith:alpine_highlands > terralith:arid_highlands
terralith:terralith:cold_shrubland > terralith:hot_shrubland
terralith:frozen_cliffs > minecraft:stony_peaks
terralith:glacial_chasm > minecraft:windswept_hills
terralith:ice_marsh > minecraft:swamp
terralith:rocky_shrubland > terralith:savanna_badlands
terralith:shield > terralith:red_oasis
terralith:siberian_grove > terralith:red_oasis
terralith:siberian_taiga > terralith:hot_shrubland
terralith:snowy_badlands > terralith:savanna_badlands
terralith:snowy_cherry_grove > minecraft:wooded_badlands
terralith:snowy_maple_forest > terralith:hot_shrubland
terralith:snowy_shield > terralith:red_oasis
terralith:wintry_forest > terralith:savanna_badlands
terralith:wintry_lowlands > terralith:hot_shrubland
terralith:fractured_savanna > minecraft:savanna
